#!/bin/bash
set -e;
export LC_NUMERIC=C;

### Script directory.
SDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
### Load useful functions.
. "${SDIR}/parallel-kaldi-functions.inc.sh" || ( \
    echo "ERROR: Sourcing file \"${SDIR}/parallel-kaldi-functions.inc.sh\"">&2 \
    && exit 1);

# lattice-scale options
acoustic_scale=1;
acoustic2lm_scale=0;
inv_acoustic_scale=1;
lm_scale=1;
lm2acoustic_scale=0;
# lattice-add-penalty options
word_insertion_penalty=0;
# QSub options
qsub_opts="-l h_rt=24:00:00,h_vmem=4G";
# Custom options
gzip=true;
overwrite=false;
word_symbol_table="";
write_best_words=false;
write_best_align=false;
help_message="
Usage: parallel-kaldi-lat-scale-qsub [options] lat1 [lat2 ...] work_dir

Description:
   Scale the acoustic and graph scores in a set of lattices and add a word
   insertion penalty.

   In order to scale similar parameters to HTK's grammar scale factor and
   word insertion penalty, use the options --inv_acoustic_scale and
   --word_insertion_penalty respectively. Notice, however, that the LM scaling
   is not 100% equivalent to HTK's.

   The input lattice strings are rxspecifiers (see Kaldi's documentation).
   As many processes as input lattices will be launched in parallel using the
   Sun Grid Engine (qsub).

   The scaled version of the lattices will be written to the work directory
   into new ARK files, named lattice.0.ark, lattice.1.ark, etc.

   e.g: parallel-kaldi-lat-scale-qsub ark:lat1.ark ark:lat2.ark wdir

Options:
  --acoustic_scale             : (float, default = $acoustic_scale)
                                 Scaling factor for acoustic likelihoods.
  --acoustic2lm_scale          : (float, default = $acoustic2lm_scale)
                                 Add this times original acoustic costs to LM
                                 costs.
  --gzip                       : (boolean, default = $gzip)
                                 If true, compress the output files using gzip.
  --inv_acoustic_scale         : (float, default = $inv_acoustic_scale)
                                 An alternative way of setting the acoustic
                                 scale: you can set its inverse. Use this as a
                                 replacement of HTK's grammar scale factor.
  --lm_scale                   : (float, default = $lm_scale)
                                 Scaling factor for graph/lm costs.
  --lm2acoustic_scale          : (float, default = $lm2acoustic_scale)
                                 Add this times original LM costs to acoustic
                                 costs.
  --overwrite                  : (boolean, default = $overwrite)
                                 If true, overwrite previously created files.
  --qsub_opts                  : (string, default = \"$qsub_opts\")
                                 Options passed to the qsub command. Note:
                                 -cwd and -t are automatically set.
  --word_insertion_penalty     : (float, default = $word_insertion_penalty)
                                 Word insertion penalty. Word means the symbols
                                 of the output alphabet in the lattice. This is
                                 equivalent to HTK's word insertion penalty.
  --word_symbol_table          : (string, default = \"$word_symbol_table\")
                                 Symbol table for words (for debug output).
  --write_best_align           : (boolean, default = $write_best_align)
                                 If true, writes an ARK file with the 1-best
                                 alignment hypothesis in the output directory.
  --write_best_words           : (boolean, default = $write_best_words)
                                 If true, writes an ARK file with the 1-best
                                 word sequence hypothesis in the output
                                 directory.
";
. "${SDIR}/parallel-kaldi-cmd-parse.inc.sh" || \
    error "Sourcing file \"${SDIR}/parallel-kaldi-cmd-parse.inc.sh\"";
[ $# -eq 0 ] && echo "$help_message" >&2 && exit 1;
[ $# -lt 2 ] && error "Wrong number of arguments. Check the usage with --help";
[ "$write_best_align" = true ] && write_best_words=true;

lats=();
while [ $# -gt 1 ]; do lats+=("$1"); shift; done;
wdir="$1";

make_dirs "$wdir";

# Check previous results, in order to avoid re-doing work.
pending_lats=();
for i in $(seq 1 ${#lats[@]}); do
    olattice="$wdir/lattice.$[i-1].ark";
    owords="$wdir/words.$[i-1].ark";
    oalign="$wdir/align.$[i-1].ark";
    [[ "$overwrite" = false && $(check_gzipped_files "$olattice") && \
        ( "$write_best_words" = false || $(check_gzipped_files "$owords") ) && \
        ( "$write_best_align" = false || $(check_gzipped_files "$oalign") ) ]] \
        && continue;
    pending_lats+=("$i");
    # Remove previous results, just in case.
    rm -f "$olattice"{,.gz} "$owords"{,.gz} "$oalign"{,.gz};
done;
if [ ${#pending_lats[@]} -eq 0 ]; then
    # No pending lattices to process. Exit normally.
    exit 0;
elif [ ${#pending_lats[@]} -eq ${#lats[@]} ]; then
    # All input lattice partitions must be processed.
    qsub_tasks="1-${#lats[@]}";
else
    # Only a subset of the input lattices must be processed.
    qsub_tasks="$(echo "${pending_lats[@]}" | sed "s| |,|g")";
fi;

{
cat <<EOF
#!/bin/bash
#$ -cwd
#$ -t ${qsub_tasks}
#$ ${qsub_opts}
set -e;
EOF
for i in ${pending_lats[@]}; do
    olattice="$wdir/lattice.$[i-1].ark";
    owords="$wdir/words.$[i-1].ark";
    oalign="$wdir/align.$[i-1].ark";
    if [ "$gzip" = true ]; then
        olattice_wspec="ark:|gzip -c -9 > $olattice.gz";
        olattice_rspec="ark:gunzip -c $olattice.gz|";
        owords_wspec="ark:|gzip -c -9 > $owords.gz";
        oalign_wspec="ark:|gzip -c -9 > $oalign.gz";
    else
        olattice_wspec="ark:$olattice";
        olattice_rspec="ark:$olattice";
        owords_wspec="ark:$owords";
        oalign_wspec="ark:$oalign";
    fi;
    echo "[[ \${SGE_TASK_ID} -eq $i ]] && {";
    cat <<EOF
    [[ "$overwrite" = false && ( -s "$olattice" || -s "$olattice.gz" ) ]] || \\
      ( lattice-scale --acoustic-scale="$acoustic_scale" \\
        --acoustic2lm-scale="$acoustic2lm_scale" \\
        --inv-acoustic-scale="$inv_acoustic_scale" \\
        --lm-scale="$lm_scale" \\
        --lm2acoustic_scale="$lm2acoustic_scale" \\
        "${lats[i-1]}" ark:- | \\
        lattice-add-penalty --word-ins-penalty="$word_insertion_penalty" \\
        ark:- "$olattice_wspec" ) \\
        &> "$wdir/lattice-scale.$[i-1].log" || {
          echo "\$(date "+%F %T") [${0##*/}:${LINENO}] ERROR: lattice-scale failed, see log file \"$wdir/lattice-scale.$[i-1].log\"" >&2; exit 1;
        }
EOF
    if [ "$write_best_words" = true ]; then
        cat <<EOF
    [[ "$overwrite" = false && ( -s "$owords" || -s "$owords.gz" ) && \\
      ( "$write_best_align" = false || -s "$oalign" || -s "$oalign.gz" ) ]] || \\
      lattice-best-path --acoustic-scale="$acoustic_scale" --lm-scale="$lm_scale" \\
      --word-symbol-table="$word_symbol_table" "$olattice_rspec" \\
      "$owords_wspec" \\
      $([ "$write_best_align" = true ] && echo "\"$oalign_wspec\"") &> "$wdir/lattice-best-path.$[i-1].log" || {
        echo "\$(date "+%F %T") [${0##*/}:${LINENO}] ERROR: lattice-best-path failed, see log file \"$wdir/lattice-best-path.$[i-1].log\"" >&2; exit 1;
      }
EOF
    fi;
    echo "}";

done;
} | qsub | awk '/Your job/{ gsub(/\..*/, "", $3); print $3}' || \
    error "qsub job submission failed!";

exit 0;